name: Build and Deploy to GitHub Pages

on:
  schedule:
    # UTC zamanÄ±nda, her gÃ¼n saat 02:00
    - cron: '0 23,4,16,19 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:4.14.1-20231025
      options: --user root --shm-size=4gb

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
          apt-get update
          apt-get install -y maven

      - name: Build and Run Scraper
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_USER }}  # ðŸ”¹ iÅŸte burasÄ±
        run: mvn clean compile exec:java

      - name: Upload public directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-html
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: scraper

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download public directory artifact
        uses: actions/download-artifact@v4
        with:
          name: public-html
          path: ./public

      - name: Deploy to pages branch safely
        run: |
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ðŸ“¦ Update public HTML $(date +'%Y-%m-%d %H:%M')"
          git branch -M main
          git push --force "https://${{ secrets.DEPLOY_TOKEN_CONTROL }}@github.com/sukrutureli/bettingsukru.git" main

